
* About this project

The original dft-book was written for VASP. In this project, we are rewriting most of that book for use with Quantum Espresso and Google Colab.

Google Colab is a free service similar to Jupyter notebooks. Zack Ulissi worked out how to install all the libraries needed to run Quantum Espresso in a Colab notebook. This is not a production DFT service. We don’t know the limitations on how big or how many calculations you can run. The examples in the tutorials have worked for us. We hope they work for you!

Please get in touch if you would like to make contributions, or even give some of the lessons.

March 22, 2020: Pretty soon we are planning to host some live webinars on running these. Stay tuned here or on Twitter for the announcements.

* Topics

1. Intro to ASE - atoms, building them, atoms properties, etc. some visualization of them. [[01-intro-to-ase.ipynb][notebook]]
2. Calculations on molecules, energy/forces, optimization, including idea of convergence. [[02-molecules.ipynb][notebook]]
3. Reactions with molecules, reaction energies, barriers
4. bulk systems, structure calculations, EOS, elastic properties, comparison of bulk phase stability
5. bulk formation energies, phase diagrams
6. surface calculations, relaxations, surface energy
7. adsorption energies, surface reactions, barriers
8. Effects of XC functional on these things?
9. atomistic thermodynamics
